class PolicyTexts {
  static const String terms = '''
TERMS OF USE (T&C)

The Users are advised to read and understand these Terms carefully before using the Services and the same shall be binding on the Users without any objection.

INTRODUCTION

This document is an electronic record as per the terms of the Information Technology Act, 2000 and rules made thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000 time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 which require publishing the rules and regulations, privacy policy, and terms of use for access or usage of the platform.

Part I and Part II of these terms of use shall be collectively referred to as the ‘terms’ and shall always be read together.

DEFINITIONS

For the purpose of these Terms, wherever the context requires, the term:

“VIKAONE” or “Payvika” or “Company” shall mean Payvika India Technology Private Limited, a Private Limited Company incorporated under the Companies Act, 2013 with its registered office at D36 S/F Ganesh Nagar, Pandav Nagar, Complex, New Delhi, 110092, Delhi. / Office Address- KHASRA NO- 150, A2Z ROAD, ALMASPUR, MUZAFFARNAGAR, U.P, 251001.

“User” shall mean any person using the platform (including but not limited to Customer).

“Customer” shall mean any person, who as the counterparty transacts using the platform for buying Gold/Silver (as defined below), taking delivery of Gold/Silver, and/or selling back the Gold/Silver to Payvika India Technology Private Limited or any other buyer as outlined in these Terms.

“Gold” shall mean 24-karat gold of 99.9% purity, offered to the Customer by Payvika India Technology Private Limited under the brand name “VIKAONE”.

“Silver” shall mean 24-karat silver of 99.9% purity or higher, offered to the Customer by Payvika India Technology Private Limited under the brand name “VIKAONE”.

“VikaOne Wallet” shall mean the account created whether by you or otherwise, in accordance with these Terms.

“VikaOne Wallet Information” shall mean the information provided by You for the purpose of creating the VIKAONE Account.

“Customer Request” shall mean a Delivery Request, Sale Request, or Exchange Request placed by You in relation to the Customer VIKAONE balance/assets.

“Force Majeure Event” shall mean any event that is beyond the reasonable control of Payvika India Technology Private Limited and shall include (without any limitation) sabotage, fire, flood, explosion, an act of God, civil commotion, strikes, lockouts or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, civil disturbances, unauthorized access to computer data and storage device, computer crashes, virus attacks, breach of security and encryption, and any other similar events not within the control of Payvika India Technology Private Limited and which Payvika India Technology Private Limited is not able to overcome.

“Payment Instrument” shall mean any electronic or written cheque, draft, money order, or other electronic or written instrument or order for the transmission or payment of money, whether or not the instrument is negotiable.

“Person” shall mean an individual, a corporation, a partnership, a joint venture, a trust, an unincorporated organisation, and any other legal entity as defined as per Income Tax Act, 1961.

“Platform” shall mean, and include the mobile application and website by the name and style of “www.vikaone.com”, that the Customer accesses for the transactions, including all contents, services, and technology offered through the Platform.

“Transfer” refers to a facility to transfer Gold/Silver from a VikaOne Wallet to another VikaOne Wallet.

“Threshold Quantity” refers to the minimum weight of gold/silver required for delivery as specified by the platform & may change from time to time.

In addition to the terms defined herein, additional terms used shall have the respective meanings assigned thereto in the relevant sections contained hereinafter.

TERMS AND CONDITIONS OF SERVICES BEING PROVIDED BY PAYVIKA INDIA TECHNOLOGY PRIVATE LIMITED

Payvika India Technology Private Limited will be selling gold/silver and providing services of safekeeping/vaulting and delivery/fulfillment of gold/silver and related services to the Customers, on or through the Platform (“Services”).

The Gold/Silver is being offered for purchase and/or sale by Payvika India Technology Private Limited under its brand name “VIKAONE”. The Services are being provided by Payvika India Technology Private Limited, however, Payvika India Technology Private Limited may utilize any external Payment Gateway Service (“PG Service”) for facilitating the collection of payments for the Services on its Platform. The PG Service Provider assumes no liability for the Services except for providing payment services and Customer Support in addressing the queries related to payments made. Any and all of the transactions relating to the Services are being rendered by Payvika India Technology Private Limited in association with the Intermediaries (Known as Vault Keeper) with whom separate agreements have been entered into by Payvika India Technology Private Limited.

The users are advised to read and understand these Terms carefully before using the Services and the same shall be binding on the users without any objection.

Payvika India Technology Private Limited does not guarantee any returns, on any transactions consummated vis-à-vis the Platform, to any person, either directly or indirectly. The investment of the Customer is solely the responsibility of the Customer. The Customer assures that the customer shall not hold VIKAONE liable in any circumstances. The Customer (hereinafter referred to as “You”, with the term “Your” being construed accordingly) shall be solely responsible for undertaking appropriate and effective due diligence and market and related analysis before undertaking any transactions pursuant to these Terms of Use. The customer shall analyse the investment and benefits and losses of the investment. You further acknowledge and agree that Payvika India Technology Private Limited and its officers, directors, employees, agents, and affiliates will have no liability for Your purchase or other decisions using the Platform.

The Services by Payvika India Technology Private Limited shall be provided for a term commencing from the date of creation of the VIKAONE Account.

You understand and acknowledge that the Services are being provided and made available on an “AS IS” and “AS AVAILABLE” basis. Due to technical reasons which may not be known to Payvika India Technology Private Limited, The Platform may contain errors or inaccuracies that could cause failures, corruption, or loss of data and/or information from Your device and/or any device used by You to connect to the Platform as well as from peripherals (including, without limitation, servers and computers) connected to any of the above-mentioned devices. You assume all risks and costs associated with Your use of the Services and the Platform, including without limitation, any costs incurred for the use of Your device and any damage to any equipment, software, or data. You agree to such technical defaults and liabilities.

You confirm that you are not registered under the Goods and Services Tax Act, 2017 and that if, in the course of your relationship with Payvika India Technology Private Limited, you become registered under the Goods and Services Tax Act, 2017, you shall inform Payvika India Technology Private Limited of your change in status immediately, and provide any relevant information and documents, as may be requested.

VAULT KEEPER, INTERMEDIARIES, AND SAFEKEEPING ARRANGEMENT

Payvika India Technology Private Limited or the Vault Keeper (as the case may be) may from time to time appoint intermediaries who shall assist Payvika India Technology Private Limited in providing the Services to You. The term, “Intermediaries” shall mean & include the Vault Keeper, and shall include any and all Persons appointed by Payvika India Technology Private Limited or the Vault Keeper (as the case may be) upon placement of an Order. You hereby consent to the appointment of such Intermediaries, for and on Your behalf, by Payvika India Technology Private Limited or the Vault Keeper (as the case may be). Any default by such intermediaries shall not be the liability of Payvika India Technology Private Limited.

You acknowledge and understand that these Intermediaries have been appointed to ensure that Your Orders/Customer Requests are duly complied with in accordance with these Terms. You additionally acknowledge that certain payments will have to be made to these Intermediaries for their appointment and services in relation thereto, which shall be borne by Payvika India Technology Private Limited on Your behalf unless otherwise indicated in these Terms.

You hereby acknowledge and agree that in order to ensure that Your Orders/Customer Requests are fulfilled in all circumstances, a first and exclusive charge on the Gold/Silver by way of allocating the same amount of Gold & Silver with the Vaulting Agent.

By way of these Terms, you authorize the Vaulting Agent to act on Your behalf to ensure that Your interests are adequately protected.

Gold/Silver purchased by You corresponding to the Order shall be stored with a Vaulting Agent in a vault on Your behalf. (Known as “Vault Keeper”)

You hereby authorize:
1. Appointment of such Vault Keeper to safe keep the gold/silver purchased; and
2. Payvika India Technology Private Limited to store such gold/silver products purchased by You, including, but not limited to, bullion, coins or jewelry (as the case may be) in the secured vault on Your behalf (“Gold/Silver”).

It is hereby clarified that Your purchase of the gold/silver corresponding to the Order shall be deemed to be completed and title in relation thereto shall be deemed to have been passed upon relevant portion of the Gold/Silver being stored in the vault with the Vault Keeper on Your behalf or upon a final invoice being issued by Payvika India Technology Private Limited in accordance with these Terms, subject to applicable laws.

To ensure that the Gold/Silver stored in such vault is adequately protected, necessary insurance policy/ies have been obtained by the Vault Keeper, where the cost of insurance to safe keep the same will be borne by the Vault Keeper/Payvika India Technology Private Limited. Pursuant to such insurance policy/ies, for any loss or damage to the Gold/Silver stored in the vault, You further authorize the Vault Keeper to act as Your beneficiary under the insurance policy/ies and to take all steps necessary to protect Your interests.

While the Vault Keeper has taken the necessary insurance policy/ies, in case of the occurrence of an event not covered in such insurance policy/ies, the Gold/Silver may be at risk. The insurance policy/ies obtained by the Vault Keeper are in line with global industry practices and cover losses due to fire, lightning, theft, cyclone, earthquake, flood, etc.

It is hereby advised that you read all the third-party service provider terms & conditions as Your acceptance of all their terms and conditions will be considered.

TRANSFER OF GOLD/SILVER

Payvika India Technology Private Limited may offer You the ability to transfer your gold/silver to another recipient, by means of the “gift” feature, or as part of another product function, such as exchanges.

Any such transfer of gold/silver from you to another recipient shall only be valid if exercised through a method or functionality offered by Payvika India Technology Private Limited.

Payvika India Technology Private Limited shall not be responsible for the acceptance or rejection of the “gift” by the intended Recipient, or for verifying the correctness of the mobile number or other identifying information provided for the intended Recipient by the Customer.

Gold/Silver gifts shall be final, and Payvika India Technology Private Limited shall not be responsible for amending, altering or otherwise reversing the transaction in case the gift is delivered to an unintended recipient due to an error on the part of the Customer.

STORAGE OF GOLD/SILVER

You are required to take delivery of Your Gold/Silver within such maximum period as shall be specified for this purpose by Payvika India Technology Private Limited from time to time on the Platform (“Maximum Storage Period”). For the purposes of making the delivery to You, you are required to provide a valid address and/or any other documents/information/ biometric identification that may be specified in this regard by Payvika India Technology Private Limited from time to time. You may provide such an address at any time during the Maximum Storage Period. In the event that no valid address has been provided by You during the Maximum Storage Period, then Payvika India Technology Private Limited shall, for a period 1 year commencing from the date of expiry of the Maximum Storage Period (such period being the “Grace Period”), attempt at least once to contact You using the contact information provided by You to obtain either:
1. an address to which You would require the gold/silver in question to be delivered, or
2. Your bank account details into which sale proceeds of the Gold/Silver shall be deposited.

In the event that Payvika India Technology Private Limited has not been able to contact You during the applicable Grace Period using the contact information provided by You or where You shall during the Grace Period either fail to:
(a) take delivery of the gold/silver in question for any reason whosoever (including where You shall not have provided any address to take delivery of such gold/silver); or
(b) provide the details for a valid bank account into which the proceeds of any sale of such Gold/Silver are to be deposited;

then upon expiry of the applicable Grace Period for the Gold/Silver in question, Payvika India Technology Private Limited shall purchase such Gold/Silver with the purchase price being the applicable prevailing price displayed on the Platform for purchase of gold/silver from Customers. The purchase proceeds realized from such sale (“Final Sale Proceeds”) after deducting any amounts payable to Payvika India Technology Private Limited as storage charges for storage of such gold/silver after the Free Storage Period.

In the event that You shall during a period of 7 days commencing from the date of expiry of the applicable Grace Period (Grace Period is 1 year from free storage period) (such period being the “Final Claim Period”) notify either Payvika India Technology Private Limited or the Vaulting Agent that You are claiming the applicable Final Sale Proceeds, shall issue suitable instructions to transfer the Final Sale Proceeds to such bank account as You shall notify for this purpose. Please note that to claim the Final Sale Proceeds You will be required to provide details of a valid bank account and that the Final Sale Proceeds will not be transferred in the absence of such details. At no time will the Final Sale Proceeds be paid to you in cash. In the event that You shall not claim Your Final Sale Proceeds within the Final Claim Period, then the Final Sale Proceeds shall be transferred to government relief funds or such other fund as Payvika India Technology Private Limited may designate for this purpose from time to time.

FORCE MAJEURE

If performance under these Terms is prevented, restricted, delayed or interfered with by reason of labor disputes, strikes, acts of God, floods, lightning, severe weather, shortages of materials, rationing, inducement of any virus, Trojan or other disruptive mechanisms, any event of hacking or illegal usage of the Platform Change in any Government Policy, utility or communication failures, earthquakes, war, revolution, acts of terrorism, civil commotion, acts of public enemies, blockade, embargo or any law, order, proclamation, regulation, ordinance, demand or requirement having legal effect of any government or any judicial authority or representative of any such government, or failure of any device used to access the Platform, or any other act whatsoever, whether similar or dissimilar to those referred to in this section, which are beyond the reasonable control of Payvika India Technology Private Limited and could not have been prevented by reasonable precautions then Payvika India Technology Private Limited shall be discharged from such performance to the extent of and during the period of such force majeure event. Such non-performance by Payvika India Technology Private Limited shall, in no manner whosoever, amount to a breach of its obligations herein.

GOVERNING LAW AND DISPUTE RESOLUTION

These Terms shall be governed by and interpreted and construed in accordance with the laws of India. The courts of New Delhi shall have exclusive jurisdiction over any disputes arising under these Terms. In the event of any dispute arising out of these Terms, the same shall be settled by binding arbitration conducted by a sole arbitrator, appointed jointly by both parties and governed by the Arbitration and Conciliation Act, 1996. The venue of arbitration shall be New Delhi, India.

CREATION OF VIKAONE ACCOUNT AND REGISTRATION OBLIGATIONS

The User shall follow the instructions on the platform for opening a VIKAONE Account & provide all required information such as Name, Age, Gender, contact information or any information as Payvika India Technology Private Limited may deem fit to ask for the process of registration. Payvika India Technology Private Limited shall be entitled to collect & verify your contact information via OTP or any other verification method.

Prior to placing an order for delivery, you may be required to provide certain KYC documentation and other information as may be required by Payvika India Technology Private Limited in such form and manner as it may deem fit. This information may be requested from you at the time of purchase in case your transaction exceeds ₹50,000/- or at any time that Payvika India Technology Private Limited may deem fit.

You authorize Payvika India Technology Private Limited to make such inquiries as may be necessary to satisfy the validity of your identity. You shall be responsible for the correctness of the information provided to Payvika India Technology Private Limited. If You have reasons to believe that there is an error in the information furnished by You, You shall immediately provide correct/updated information.

Payvika India Technology Private Limited reserves the right to terminate any VIKAONE Account, with or without notice to You, in the event the KYC documents/information are found to be incorrect or the authenticity of the documents/information is found to be doubtful. You hereby undertake to indemnify and keep indemnified Payvika India Technology Private Limited against any and all losses, claims, liabilities, costs, etc. which arise out of or relate to Your failure to identify Yourself and validate Your account promptly and/or due to incorrect KYC documents/information.

Know Your Customer (KYC) and Verification

Once the registration process is complete, You shall be entitled to place an order on the Platform (“Orders”).

You agree that Your continued use of the Platform, consequent upon the creation of the VIKAONE Account, is subject to verification by Payvika India Technology Private Limited of the information and documentation provided by You. You hereby grant Payvika India Technology Private Limited permission to conduct such verification, in such form and manner as it may deem fit.

You further acknowledge that Payvika India Technology Private Limited reserves the right for such verification either on registration of the VIKAONE Account or at any time thereafter. You hereby authorise Payvika India Technology Private Limited to engage with any third-party service provider for verification of your KYC documentation to ascertain your eligibility. Any processing undertaken by Payvika India Technology Private Limited to process KYC documents shall be in accordance with its privacy policy and these Terms. It is hereby clarified that as far as the permission to access the KYC documents by a third-party service provider is concerned, the same shall be governed by the privacy policy of such third-party service providers & payment gateways.

Customer’s Obligations

Prior to placing an order for delivery/Sell/Gift, you may be required to provide certain KYC documentation and other information as may be required by Payvika India Technology Private Limited in such form and manner as it may deem fit.

You will be responsible for maintaining the confidentiality of the VIKAONE Account Information and shall be fully responsible for all activities that occur under the VIKAONE Account. You agree to immediately notify Payvika India Technology Private Limited of any unauthorised use of the VIKAONE Account Information or any other breach of security. Payvika India Technology Private Limited cannot and will not be liable for any loss or damage arising from Your failure to comply with this section. You may be held liable for losses incurred by Payvika India Technology Private Limited or any user or visitor of the Platform due to authorised or unauthorised use of the VIKAONE Account, as a result of your failure in keeping the VIKAONE Account Information confidential.

You shall ensure that the VIKAONE Account Information provided by You in the registration form is complete, accurate, and up-to-date. Use of another Customer’s account information for availing of any of the Services and/or for use of the Platform is expressly prohibited.

You agree that if You provide any information that is untrue, inaccurate, not current, or incomplete, (or becomes untrue, inaccurate, not current, or incomplete) or if Payvika India Technology Private Limited has reasonable grounds to suspect that such information is untrue, inaccurate, not current, incomplete, or not in accordance with these Terms, Payvika India Technology Private Limited shall have the right to indefinitely suspend or terminate or block access to the VIKAONE Account on the Platform and refuse to provide You with access to the Platform and if required forfeit / freeze the balance held in the VIKAONE account.

PURCHASE OF GOLD/SILVER

You can buy Gold/Silver worth ₹1.00 (Rupee One Only) at and above the incremental value thereof the market-linked prices of gold/silver shown on the Platform. Market-linked prices mean that these quotes are linked to the prices of gold/silver in the commercial bullion market in India.

It is hereby clarified that such market-linked prices of gold/silver shall constitute fully binding offers and would be an invitation to offer to purchase gold/silver at the said market prices to all Customers. Not with standing the foregoing, You understand that these prices may vary multiple times within a day, and accordingly, Your payment obligations for any order will depend on the market-linked prices then prevailing. While reasonable efforts will be made to offer You a competitive price for the Gold/Silver, there is no guarantee that the price offered to You will be close to or comparable with other prices available in the market.

Payment will be accepted through the payment options made available on the Platform, which may include redirection to a Payment Gateway hosted by another third-party website or platform. At the time of purchase / fulfillment / sale-back / transfer of Gold/Silver, or for any other transaction, the relevant taxes will be chargeable as per government norms. It is hereby clarified that once an Order is placed, you are not entitled to cancel the Order, provided that an Order shall stand canceled if the payment fails for any reason whatsoever.

Payvika India Technology Private Limited reserves the right to cancel an Order, at its sole discretion, if Your information, provided prior to placing the Order, is not found acceptable and Payvika India Technology Private Limited is of the opinion that You are not eligible to purchase gold/silver. The VIKAONE Account shall accordingly stand amended. Payvika India Technology Private Limited shall have the right to freeze the VIKAONE Account until it receives KYC and other documentation in a form and manner satisfactory to it.

Once the payments are received by Payvika India Technology Private Limited and the KYC information, if requested, is found acceptable, Payvika India Technology Private Limited shall issue an invoice to You confirming the Order placed within a period of 3 (Three) business days of placing such order, in a manner it may deem fit.

Not with standing anything to the contrary contained in these Terms, Payvika India Technology Private Limited shall be entitled to accept or reject a Customer, for any reason whatsoever, at its sole discretion.

In case of rejection of an Order in accordance with these Terms, where payments have been received by Payvika India Technology Private Limited, such payments shall be returned to You to the bank account linked to your account, subject to the terms and conditions indicated on the Platform.

You will be provided with free storage for your Gold/Silver for 1 year w.e.f 1st January, 2026, or for such period as more particularly stipulated by Payvika India Technology Private Limited in this regard from time to time at its sole discretion and notified to Customers on the Platform (“Free Storage Period”). After the expiry of the Free Storage Period, Payvika India Technology Private Limited shall be entitled to levy storage charges for such Gold/Silver at such rate as would be specified on the Platform, and which may be revised from time to time. The charges would be levied by deducting the Gold/Silver balance at the end of each month by a percentage amount at the specified rate. You are advised to periodically check the Platform to understand these storage charges. In the event Payvika India Technology Private Limited is not able to deduct the storage charges because Your gold/silver balance is too low, then Payvika India Technology Private Limited shall be entitled to sell such portion of Your Gold/Silver stored with the Vault Keeper that is necessary or required to recover the unpaid storage charges in question.

DELIVERY OF GOLD/SILVER

This Platform offers Services for Users who wish to procure delivery of the Gold/Silver in accordance with these Terms.

You shall be entitled to procure delivery of the Gold/Silver using the Platform (“Delivery Request”).

Upon placing the Delivery Request, you shall be required to pay for the applicable charges and confirm the Delivery Request. Your VIKAONE Account shall be provisionally debited corresponding to the quantity of the Gold/Silver sought to be delivered (“Delivered Gold/Silver”).

Within a period of 5 (Five) business days of the Delivery Request being confirmed or such further period as may be required by Payvika India Technology Private Limited, Payvika India Technology Private Limited shall arrange for delivery of the product at the shipping address indicated by You. You shall be solely responsible for ensuring that the correct address is furnished by You on the Platform for processing such Delivery Requests. You shall not be entitled to change the shipping address after the Delivery Request is processed by Payvika India Technology Private Limited.

The product shipping will be delivered within 7-8 business working days after the confirmation of delivery request.

You should carefully examine the package delivered and shall not accept deliveries where the packaging has been tampered with. If, however, You are of the view that the package delivered has been tampered with, you are required not to accept the parcel and shall be required to intimate Payvika India Technology Private Limited immediately of the same, and provide such other information as may be required by Payvika India Technology Private Limited which may require digital information like Photo & Video of the package in this regard (“Return Request”). Within a period of 1 (One) business day of the original package Gold/Silver being delivered back to Payvika India Technology Private Limited, in a manner indicated by Payvika India Technology Private Limited, and the Return Request being approved by Payvika India Technology Private Limited if the delivery has been received by you, Payvika India Technology Private Limited shall arrange for re-delivery/pick up of the Delivered Gold/Silver at the shipping address indicated by You. The costs for such shipping shall be borne by Payvika India Technology Private Limited. However, in the event of frivolous and unjustified Return Requests made by You, Payvika India Technology Private Limited reserves the right to take all action available to it, including black-listing or blocking You from using the Services on the Platform (and Payvika India Technology Private Limited shall reserve the lump sum amount as unprecedented expenses).

You, upon signing the delivery receipt, acknowledge the receipt of the Delivered Gold/Silver product in terms of the Delivery Request placed with Payvika India Technology Private Limited. Payvika India Technology Private Limited shall not be liable to You for any refund/replacement, under any circumstance, for any subsequent complaints with respect to such deliveries and/or any failure on your part (as the case may be) to comply with these Terms.

It shall be Your responsibility to ensure that You are available to receive the Delivered Gold/Silver at the time of delivery. If You are not available at the time of delivery, the Payvika India Technology Private Limited courier agent may try and deliver the item 3 consecutive attempts before returning the same to Payvika India Technology Private Limited. In case of return of the Delivered Gold/Silver to Payvika India Technology Private Limited, VIKAONE Account shall be credited for the Delivered Gold/Silver, after deducting the charges (if any) due from You, provided however that Payvika India Technology Private Limited is of the opinion that the packaging has not been tampered with. It is hereby clarified that should a request for re-delivery be made by You, you shall be solely liable to incur the applicable charges for redelivering the Delivered Gold/Silver.

In case of Payvika India Technology Private Limited’s inability to make deliveries of Delivered Gold/Silver due to a Force Majeure Event, Payvika India Technology Private Limited shall intimate You of the same within a reasonable time and may require that the deliveries be effectuated through specific modes. In such a case, you hereby agree to bear any additional costs and fees necessary for the delivery to be complete.

Payvika India Technology Private Limited will not be able to deliver a fractional quantity of gold/silver below such threshold as Payvika India Technology Private Limited shall notify for this purpose even if a Customer Request is made for such fractional quantity (“Threshold Quantity”). You are advised to check the Platform periodically to determine the Threshold Quantity as the same may be revised from time to time. In the event that any Gold/Silver below the Threshold Quantity is to be delivered to you, then please note that such Gold/Silver shall instead be sold based on the sale prices displayed on the Platform and You will instead receive the applicable sale proceeds in Your bank account, details of which are provided by You. If there is any mistake in the account number provided by You, Payvika India Technology Private Limited would not be held responsible for the same.

Notwithstanding anything to the contrary contained in these Terms, Payvika India Technology Private Limited shall be entitled to reject a Customer Request which is not in compliance with the Terms hereof and shall intimate the Customer of the reasons for the same.

Based on the changes made to the VIKAONE Account (in lieu of the Orders and/or Customer Requests), if You are of the opinion that the changes made thereto do not tally with the orders and/or Customer Requests placed by You, You may contact Payvika India Technology Private Limited at info@vikaone.com, who shall accordingly take all necessary actions for taking care of any such identified discrepancies.

It is hereby clarified that the Gold/Silver cannot be pledged by You, and the VIKAONE Account is non-transferable unless specifically allowed by Payvika India Technology Private Limited. In the event of Your death, if specifically allowed by Payvika India Technology Private Limited, the title to such Gold/Silver lying in the vault and the VIKAONE Account shall transfer to Your legal heirs only after the required due diligence has been conducted (provided that you have filled nominee details). Subsequent to this, Your legal heir(s) shall be regarded as the Customer for the purpose of the Gold/Silver and VIKAONE Account thereafter and the Terms shall be applicable to Your legal heir(s).

It is hereby clarified that the Platform displays articles that are available for shopping. Some items may appear slightly larger or smaller than the actual size due to screen defaults and photography techniques. Payvika India Technology Private Limited shall not be liable for any legal action on this account. It shall be Payvika India Technology Private Limited’s endeavour to ensure that all details regarding the product are clearly displayed on the Platform.

Due to reasons not directly attributable to Payvika India Technology Private Limited, data may be inaccurately displayed on the Platform due to some system errors on the Platform or any device used to access the Platform. Payvika India Technology Private Limited reserves the right to correct any and all errors when they do occur, at its sole discretion, and Payvika India Technology Private Limited shall be entitled to not honour any requests/orders placed by You based on any inaccurate or erroneous prices.

The prices quoted on the Platform are fixed and not negotiable. The prices on the Platform are also subject to change without notice to You.

* The return product metal grams will be re-credited to customer wallet within 3 working days.
* Customer can cancel the order request of delivery before the package is out for delivery from the mobile app and website from my order screen.

SALE OF GOLD/SILVER

You will get an option to sell the Gold/Silver based on the sale prices on the Platform. If the prices are found acceptable to You, You shall confirm the sale request, in a form and manner acceptable to Payvika India Technology Private Limited (“Sale Request”). Your VIKAONE Account shall be debited corresponding to the quantity of the Gold/Silver sought to be sold via the Sale Request.

There's a lock-in period if the customer purchases gold/silver within 48 hours so the customer can sell after 48 hours.

Within a period of 6-7 business days of the Sale Request being confirmed or such further period as may be required, the payment, pursuant to the Sale Request, shall be disbursed by Payvika India Technology Private Limited at the sale prices indicated at the time of placing such Sale Request. Payvika India Technology Private Limited shall arrange for such payments to be made to Your bank account, details of which are provided by You. If there is any mistake in the account number, IFSC code, etc. provided by You, Payvika India Technology Private Limited would not be held responsible for the same.

While reasonable efforts will be made to offer You a competitive price for Gold/Silver, there is no guarantee that the price offered to You will be close to or comparable with other prices available in the market.

For the Selling process, customers must have Minimum 1 gm of gold and Minimum 10 gm of silver in their wallet for sell.

FRAUDULENT TRANSACTIONS

The Customer should take care not to share their wallet details, personal UPI pin, or OTP (“Payment Information”) with any third party intentionally or unintentionally. The Company never solicits Payment Information over a call or otherwise. The Company/Platform/Third Party Services/Payment Gateway partners shall not be liable for any fraud due to the sharing of such details.

In the event that an individual’s Payment Information or Payment Instrument is fraudulently utilized to purchase gold/silver on the Platform (“Fraudulent Transaction”) from Payvika India Technology Private Limited, then the Company may share relevant information of such transaction if the victim approaches the Company via proper channels including Payvika India Technology Private Limited’s customer support number and email (info@vikaone.com), along with supporting documentation from the relevant authority.

In the event that Payvika India Technology Private Limited and/or the Platform Partner have flagged any transaction or Customer account as suspicious as per their internal guidelines, or where it is found that a Customer has utilized Payment Information or a Payment Instrument in an unauthorized or fraudulent manner to purchase gold/silver or undertake any other transaction on the Platform (Fraudulent User), Payvika India Technology Private Limited and/or the Platform Partner shall be entitled to request further KYC information or other documentation from the User to verify the flagged transaction; pending further verification, block such Fraudulent User, and/or freeze any accounts associated with them; reverse any such Fraudulent Transaction, to the extent possible, including the sale of any gold/silver purchased by such Fraudulent User, at the prevailing rate; provide information on such Fraudulent User, along with any other transaction details, to the relevant authorities.

In the event of a Fraudulent Transaction, Payvika India Technology Private Limited shall make a reasonable effort to assist the victim in recovering their funds, subject to supporting evidence and documentation being provided upon request. Payvika India Technology Private Limited shall be entitled to transfer the victim’s funds, in this case, VIKAONE will deduct operation and transfer charges charged by the third-party platform.

However, it is clarified that Payvika India Technology Private Limited shall not obligate to reverse any transaction where the Fraudulent User has already sold the gold/silver purchased through the Fraudulent Transaction and received the funds against such sale; or where the fraudulent User has chosen to take delivery of the gold/silver so purchased. In this event, Payvika India Technology Private Limited shall, to the best of its ability, provide any information on the fraudulent User, including the bank account or VikaOne Wallet account to which funds have been settled, or the physical address to which the gold/silver has been delivered, to the victim or the relevant authorities.

USE OF THE PLATFORM AND SERVICES

You acknowledge that the Services are for Your personal use and agree not to publish the gold/silver prices or descriptions of gold/silver and/or any other information displayed on the Platform (in lieu of Your access to the Platform) on any other medium. You shall not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products, or services obtained from the Services.

Subject to these Terms and the Privacy Policy, You hereby grant to Payvika India Technology Private Limited a non-exclusive, worldwide, royalty-free right to (a) collect, store and transmit Your data, in each case solely to the extent necessary to provide the Services to You, and (b) share Your data or interact with other people, to distribute and publicly perform and display Your Data as You direct or enable through the Services. You will provide Your consent to Payvika India Technology Private Limited as may be required under applicable law for the use and/or sharing of any data generated by You when purchasing Gold/Silver or otherwise using the Platform for any services related to the purchasing of the Gold/Silver in such manner as Payvika India Technology Private Limited may stipulate in this regard. Payvika India Technology Private Limited may share Your data with the Vault Keeper, as required, to fulfill their obligations as a Vault Keeper. Your data will continue to be governed by confidentiality obligations. It is hereby clarified that Payvika India Technology Private Limited would be the owner of any data generated by You when purchasing the Gold/Silver on the Platform.

You represent and warrant that: (i) You have obtained all necessary rights, releases, and permissions to provide all Your data to Payvika India Technology Private Limited and to grant the rights granted to Payvika India Technology Private Limited in these Terms and (ii) Your data and its transfer to and use by Payvika India Technology Private Limited as authorized by You under these Terms do not violate any laws or rights of any third party, including without limitation any intellectual property rights, rights of privacy, or rights of publicity, and any use, collection, and disclosure authorized herein is not inconsistent with the terms of any applicable privacy policies. Other than its security obligations under these Terms and the Privacy Policy, Payvika India Technology Private Limited assumes no responsibility or liability for Your data, and You shall be solely responsible for Your data and the consequences of using, disclosing, storing, or transmitting it.

Payvika India Technology Private Limited shall not be held liable for any loss of data, technical or otherwise, information, or for particulars supplied by You, due to reasons beyond its control like corruption of data or delay or failure to perform as a result of a Force Majeure Event.

Payvika India Technology Private Limited shall have the sole discretion to determine the locations and pin codes it may want to serve.

The provision of Services may be interrupted, including for maintenance, repairs, upgrades, or network or equipment failures. Payvika India Technology Private Limited strives to keep the Services up and running; however, all online services suffer occasional disruptions and outages. Payvika India Technology Private Limited is not liable for any disruption or loss You may suffer as a result.

Payvika India Technology Private Limited may discontinue some or all of the Services, including certain features and the support for certain devices and platforms, at any time.

Storage charges are applicable to the user as per this terms of use & in case of failure of receipt of charges, Payvika India Technology Private Limited shall remind the user for the payment & shall only wait for 1 year from the due date of payment, thereafter, the charges should be recovered from your possession and the remaining amount shall be transferred to government relief funds if the default persist.

SUSPENSION / CLOSURE OF VIKAONE ACCOUNT

Payvika India Technology Private Limited may, at its discretion, suspend the VIKAONE Account of Customers, if there appears to be fraudulent or suspicious activity in the account. If Payvika India Technology Private Limited is of the opinion that You are involved in any unlawful activity or the VIKAONE Account is used for any unlawful purpose, Payvika India Technology Private Limited shall have the right to take all actions available to it, including black-listing or blocking You from using the Services on its Platform or blocking Your access to the Services through the Platform or intimating the relevant authorities of such unlawful activities.

Payvika India Technology Private Limited shall not be held liable/responsible, in any manner whatsoever, for any loss/liability arising out of or relating to any technical failure/issue in Platform and/or acts/omission not attributable to it.

You shall inform immediately, in any case within 24 hours after the transaction, of any irregularities or discrepancies that may exist in Your VIKAONE Account, failing which it shall be deemed that there is no error or discrepancy in the account. All records maintained by Payvika India Technology Private Limited, in electronic or documentary form of the instructions of the Customer and such other details (including but not limited to payments made or received) pursuant to the Terms, shall as against the Customer, be deemed to be conclusive evidence of such instructions.

FEES

You hereby agree that You shall be liable for all fees and charges associated with the use of the Platform and Services. Further, details of the fees payable (including, but not limited to the terms pertaining to such fees and the quantum thereof), have been set out on the Platform. Please note that the fees and charges may be revised from time to time and it would be Your responsibility to view the Platform to check the then current fees and charges payable.

It is hereby clarified that fees and charges, once paid, are non-refundable if any.

All payments made for the use of the Platform and/or purchase of Gold/Silver by You shall be compulsorily in Indian Rupees.

While availing any of the payment method/s available on the Platform for availing the Services, Payvika India Technology Private Limited shall not be responsible for or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:
1. Lack of authorization for any transaction(s), or
2. Exceeding the preset limit mutually agreed by You and between bank/s and/or other institutions used by you in making payment, or
3. Any payment issues arising out of the transaction, or
4. Rejection of transaction for any other reason(s) whatsoever.

Payvika India Technology Private Limited may temporarily/permanently suspend/terminate the VIKAONE Account or refuse access in case of non-payment of fees due by You. Without limitation to the other rights and remedies available to Payvika India Technology Private Limited, it also reserves the right to take legal action for the same.

MEMBER ELIGIBILITY

Use of the Platform and/or the Services is available only to Persons who can enter into legally binding contracts under the Indian Contract Act, 1872, and to a person resident in India having active and valid PAN & Other Legal ID Proofs as per the Indian Laws & Regulations. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents, and persons of unsound mind are not eligible to use the Platform or the Services. Any person under the age of 18 shall not register on the Platform and shall not transact on or use the Platform in relation to or for any Services. Payvika India Technology Private Limited reserves the right to terminate any Person’s membership and/or refuse to provide such Person with access to the Platform and/or any Services if it is brought to Payvika India Technology Private Limited’s notice or if it is discovered that such Person is not eligible to use the Platform and/or any Service.

ABSENCE OF RELATIONSHIP

You represent and warrant to Payvika India Technology Private Limited that you have sufficient experience and knowledge to make informed decisions regarding the transactions which are provided on the VIKAONE platform. You acknowledge that you have not relied on any information made available by Payvika India Technology Private Limited and that Payvika India Technology Private Limited is not making any recommendation with respect to any of such transactions. No relationship other than seller-purchaser, including, without limitation, any agent-principal relationship, any advisor-advisee relationship, any employee-employer relationship, any franchisee-franchisor relationship, any joint venture relationship or any partnership relationship, exists between you & Payvika India Technology Private Limited.

You acknowledge that Payvika India Technology Private Limited does not provide / dealing in / offering any investment product and does not offer any guarantee/assured returns. You further acknowledge that the value of Gold/Silver may vary depending on various factors and forces.

ELECTRONIC ORDER RISKS

Commercial internet & Related service providers are not 100% reliable and a failure by one or more of these providers may affect internet-based order entry. You acknowledge that the order entry system is an electronic mechanical system and as such may be subject to failure beyond the control of Payvika India Technology Private Limited. Therefore, Payvika India Technology Private Limited shall not be responsible for errors, negligence, inability to execute orders, delays in transmission, delivery, or execution of orders due to breakdown or failure of transmission or communication facilities (including in any device used to connect to the Platform), or to any other cause beyond Payvika India Technology Private Limited’s control or anticipation.

FEEDBACK

The Platform may allow You to post Your review and experience of using the Platform ("Reviews") in order to improve the Platform and the user experience.

You, being the originator of the Reviews, are responsible for the Reviews that You upload, post, publish, transmit or otherwise make available on the Platform. You represent that all such Reviews will be in accordance with applicable law. You acknowledge that Payvika India Technology Private Limited does not endorse any Reviews on the Platform and is not responsible or liable for any Reviews. Payvika India Technology Private Limited reserves the right to disable access to the Reviews on the Platform.

You hereby grant Payvika India Technology Private Limited a perpetual, non-revocable, worldwide, royalty-free, and sub-licensable right and license to use, copy, distribute, display, publish, transmit, make available, reproduce, modify, adapt the Reviews in any manner as deemed appropriate by Payvika India Technology Private Limited in any form including but not limited to print, broadcast, online and across any and all websites and platforms owned by Payvika India Technology Private Limited.

You further represent and warrant that while posting any Reviews on the Platform You shall not use any offensive, libelous, derogatory, hateful, or racially or ethnically objectionable language. Further, You shall not post any content on any part of the Platform that is obscene, pornographic, or constitutes an “indecent representation of women” as provided in the Indecent Representation of Women (Prohibition) Act, 1986.

CONFIDENTIALITY

As elaborated under the Privacy Policy, Payvika India Technology Private Limited will keep all confidential information confidential, including Your personal information, and shall not disclose it to anyone except as required by law, and shall ensure that such confidential information is protected with security measures and a degree of care that it would apply to its own confidential information. Payvika India Technology Private Limited acknowledges that its employees, directors, agents, and contractors shall use the confidential information only for the intended purpose for which it is provided. Payvika India Technology Private Limited shall use all reasonable endeavors to ensure that its employees, directors, agents, and contractors acknowledge and comply with the provisions of these Terms of confidentiality as if such person was subject to these Terms of confidentiality. Payvika India Technology Private Limited would not be held responsible for breach of confidentiality if it is beyond its control.

CONTENT AND INTELLECTUAL PROPERTY RIGHTS

Payvika India Technology Private Limited solely and exclusively owns respective copyrights, trademarks, service marks, logos, trade names, and other intellectual and proprietary rights associated with the Services provided by Payvika India Technology Private Limited and displayed on/accessed on the Platform and is protected under Indian law.

You hereby acknowledge that the Services constitute original works and have been developed, compiled, prepared, revised, selected, and arranged by Payvika India Technology Private Limited respectively through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes the valuable intellectual property of Payvika India Technology Private Limited and such others. You thereby agree to protect the proprietary rights of Payvika India Technology Private Limited during and after the term of these Terms. You may not selectively download portions of the Platform without retaining the copyright notices.

Any infringement shall lead to appropriate legal proceedings against You at the appropriate forum for seeking all available remedies under applicable laws of the country.

LINKS TO/FROM THIRD-PARTIES WEBSITES/APPLICATIONS

The Platform may contain links and interactive functionality interacting with the websites of third parties. Payvika India Technology Private Limited is not responsible for and does not have any liability for the functionality, actions, inactions, privacy settings, privacy policies, terms, or content of any such websites. Before enabling any sharing functions to communicate with any such website or otherwise visiting any such website, Payvika India Technology Private Limited strongly recommends that You review and understand the terms and conditions, privacy policies, settings, and information-sharing functions of each such third-party website.

INDEMNIFICATION

You hereby agree to indemnify and keep the Payvika India Technology Private Limited indemnified from and against all actions, claims, demands, proceedings, losses, damages, costs, charges, and expenses, directly or indirectly, whatsoever (“Losses”) which Payvika India Technology Private Limited and/or its Directors & Relatives, employees, agents, workers or representative or any related entities & business partners may at any time incur, sustain, suffer or be put to as a consequence of or by reason of or arising out of:
(i) The usage of the Platform and/or any device used by the Customer to access the Platform.
(ii) By reason of Payvika India Technology Private Limited acting in good faith and taking or refusing to take or omitting to take action on the Customer's instructions, and in particular arising directly or indirectly out of the negligence, mistake, or misconduct of the Customer.
(iii) Breach or non-compliance of the Terms and relating to the VIKAONE Account; and/or Fraud or dishonesty relating to any transaction by the Customer.

DISCLAIMER OF WARRANTIES

All information, content, materials, and services included on or otherwise made available to you through the platform (collectively, the "contents") are provided by Payvika India Technology Private Limited on an "as is," "as available" basis, without representations or warranties of any kind. Payvika India Technology Private Limited makes no representations or warranties of any kind, express or implied, as to the operation of the platform, the accuracy or completeness of the contents, and the accuracy of the information. Payvika India Technology Private Limited shall have no responsibility for any damage to your computer system or loss of data that results from the download of any content, materials, document, or information or any other losses incurred by you for use of the platform. You expressly agree that the use of the platform is at your sole risk. Payvika India Technology Private Limited will not be liable for any damages of any kind arising from the use of the platform or the services or the contents including, without limitation, direct, indirect, consequential, punitive, and consequential damages, unless otherwise specified in writing. To the full extent permitted by law, Payvika India Technology Private Limited disclaims any and all representations and warranties with respect to the platform (or any part thereof) and its contents, whether express or implied, including, without limitation, warranties of title, merchantability, and fitness for a particular purpose or use.

LIMITATION OF LIABILITY

You hereby acknowledge that Payvika India Technology Private Limited (including but not limited to its directors, employees, agents, or partners) shall not be held liable to You for any special, consequential, incidental, exemplary, or punitive damages, or loss of profit or revenues. Payvika India Technology Private Limited shall also not be liable under any circumstances for damages arising out or related in any way to Your inability to access, or Your difficulty in accessing the Platform to avail of any Services, any bugs, viruses, trojan horses, or the like, which may be transmitted to or through the Platform by any third party, any loss of Your data, any claim relating to Your data or content from the Services and/or Your failure to keep the VIKAONE Account Information secure and confidential. You further agree that Payvika India Technology Private Limited shall not be held responsible in any manner whatsoever for any and all acts or omissions of any Intermediaries or any other third party whosoever including (but not limited to) any person whose device has been used by You to access the Platform and/or any person appointed/nominated for the purposes of accepting/collecting any payments from You for the purchase of Gold/Silver.

AMENDMENTS, ACCEPTANCE OF TERMS

Payvika India Technology Private Limited reserves the right to change, modify, add or remove portions of these Terms at any time. Such changes shall be posted on the Platform and shall/shall not notify the Customer after making such changes. Notwithstanding anything to the contrary, Customer shall be responsible for regularly reviewing the Terms, including amendments thereto as may be posted on the Platform, and shall be deemed to have accepted the amended Terms by continuing the use of Platform.

Accessing, browsing, or otherwise using the Platform indicates Your acceptance of all the terms and conditions under these Terms. You are advised to read these Terms carefully before proceeding. By impliedly or expressly accepting these Terms, You also agree to be bound by all policies, including but not limited to Payvika India Technology Private Limited’s privacy policy (“Privacy Policy”), as amended occasionally. You can view and read Payvika India Technology Private Limited’s Privacy Policy at www.vikaone.com.

You may not use the Platform or avail yourself of the Services if You do not accept the Terms or are unable to be bound by the Terms. As a condition of Your access to and use of the Platform or the provision of any Services to You using the Platform, You agree that You will comply with all applicable laws and regulations when using the Platform. If Payvika India Technology Private Limited is of the opinion that the VIKAONE Account is being used by You for any unlawful purpose, Payvika India Technology Private Limited shall have the right to take all actions available to it, including black-listing or blocking You from using the Services through the Platform or intimating the relevant authorities of such unlawful activities.

Payvika India Technology Private Limited understand that "you acknowledge that you have read and understood the information provided above, and you agree that the company is not liable for any consequences resulting from your failure to understand or act upon this information."

GRIEVANCE REDRESSAL MECHANISM

In accordance with the Information Technology Act, 2000 and the Rules made there under:
The contact details for the purposes of Payvika India Technology Private Limited are:
• E-mail ID: info@vikaone.com
• Address: D36 S/F GANESH NAGAR, PANDAV NAGAR, COMPLEX, NEW DELHI, 110092, DELHI.
• Office Address : KHASRA NO-150, A2Z ROAD, ALMASPUR, MUZAFFARNAGAR, 251001. U.P.
''';

  static const String privacy = '''
PRIVACY POLICY

INTRODUCTION

Payvika India Technology Pvt. Ltd., a Private Limited Company Incorporated under the Companies Act, 2013 with its registered office at D36 S/F GANESH NAGAR, PANDAV NAGAR COMPLEX NEW DELHI, 110092. CORPORATE ADDRESS – KHASRA NO.150, A2Z ROAD, ALMASPUR, MUZAFFARNAGAR 251001.("Payvika India Technology Pvt. Ltd.") will be selling Gold, Silver & Related Commodities and providing services of safekeeping / vaulting and delivery / fulfillment of Gold, Silver & Related Commodities and related services thereto to the Customers, on or through the Platform (“Services”).

Payvika India Technology Pvt. Ltd. (“Company”/ “We”/ “Our”/ “Us”) is committed to protecting your privacy and grant importance to the confidentiality of your data over the internet. This privacy policy (“Privacy Policy”) shall apply to all persons using or accessing (“Users”, “You” or “Your”) any or all products, services, features, or content offered on the internet website www.vikaone.com (“Website”) and/or the mobile application “VikaOne” (“VikaOne Mobile Application”).

This Privacy Policy is an electronic record in the form of an electronic contract formed under the Information Technology Act, 2000 and the rules made thereunder and the amended provisions pertaining to electronic documents/ records in various statutes as amended by the Information Technology Act, 2000. This Privacy Policy does not require any physical, electronic, or digital signature and is a legally binding document between the User and Us.

This Privacy Policy shall be in compliance with the General Data Protection Regulation (GDPR) in effect from May 25, 2018, and any and all provisions that may read to the contrary shall be deemed to be void and unenforceable as of that date. If you do not agree with the terms and conditions of our Privacy Policy, including in relation to the manner of collection or use of your information, please do not use or access the Site. If you have any questions or concerns regarding this Privacy Policy, you should contact our Customer Support Desk at info@vikaone.com

ANY CAPITALIZED WORDS USED HENCEFORTH SHALL HAVE THE MEANING ACCORDED TO THEM UNDER THIS AGREEMENT. FURTHER, ALL HEADING USED HEREIN ARE ONLY FOR THE PURPOSE OF ARRANGING THE VARIOUS PROVISIONS OF THE AGREEMENT IN ANY MANNER. NEITHER THE USER NOR THE CREATORS OF THIS PRIVACY POLICY MAY USE THE HEADING TO INTERPRET THE PROVISIONS CONTAINED WITHIN IT IN ANY MANNER.

INFORMATION WE COLLECT

We are committed to respecting your online privacy. We further recognize your need for appropriate protection and management of any Personal Information You share with us. We may collect the following information:
• Personal data including but not limited to Username along with Password, Your Name, Your Number, and Your Email address, bank account details;
• Information is collected through the permissions we seek through the applications such as the permission to access Gallery, Contacts, notification, SMS, location & any other permissions as required.
• Tracking Information such as, but not limited to the IP address of your device and Device ID when connected to the Internet. This information may include the URL that you just came from (whether this URL is on the Platform or not), which URL you next go to (whether this URL is on the Platform or not), your computer or device browser information, and other information associated with your interaction with the Platform;
• Details of Platform usage for analytics.
• Financial data (such as account details, e-wallet details, bank account or credit or debit card details or other payment instrument details, etc.) that the User may have provided Us. We work with multiple payment processors who store these details in an encrypted format. All Our payment processors are Payment Card Industry Data Security Standard (PCI DSS) compliant.
• Personal information stored with third parties that you choose to provide to us, such as your social media account information and your social media contacts. By linking your third-party accounts or using third-party sign-in services, you authorize us to have access to this information and you agree that we may collect and use this information only in accordance with this Privacy Policy.

OUR USE OF YOUR INFORMATION

The information provided by you shall be used to provide and improve the service for you and all users.
• To provide you with services on your request.
• For maintaining an internal record.
• For enhancing the Services provided.
• For maintaining record under the legal and statutory provisions.

For more details about the nature of such communications, please refer to our Terms of Service. Further, your data and Sensitive Personal data may be collected and stored by us for internal record.

We use your tracking information such as IP addresses, and or Device ID to help identify you and to gather broad demographic information, and make further services available to you. We will not share your personal information with others unless they are acting under our instructions or we are required to do so by law.

Information collected via our server logs includes users' IP addresses and the pages visited; this will be used to manage the web system and troubleshoot problems. We also use third-party analytics, tracking, optimization, and targeting tools to understand how users engage with our Platform so that we can improve it and cater personalized content/ads according to their preferences.

COOKIES

“Cookies” are small identifiers sent from a web server and stored on your computer's hard drive, that help us to recognize you if you visit our Website/VikaOne Mobile Application again.

From time to time, we may place “cookies” on your personal computer. Also, our Website/VikaOne Mobile Application uses cookies to track how you found our Website/VikaOne Mobile Application. To protect your privacy we do not use cookies to store or transmit any personal information about you on the Internet. You have the ability to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies certain features of the Website/VikaOne Mobile Application may not function properly or at all as a result.

EXTERNAL LINKS ON THE PLATFORM

The Platform may include advertisements, hyperlinks to other websites or resources. We have no control over any other website or resources or contents available on these other websites, which are provided by companies or persons other than us. You acknowledge and agree that we are not responsible for the availability of any such external sites or resources, and do not endorse any advertising, services/services, or other materials on or available from such platform or resources. You acknowledge and agree that We are not liable for any loss or damage which may be incurred by you as a result of the availability of those external sites or resources, or as a result of any reliance placed by you on the completeness, accuracy, or existence of any advertising, services or other materials on, or available from, such websites. These external third-party websites and resource providers may have their privacy policies governing the collection, storage, retention, and disclosure of Your Personal Information that You may be subject to. We recommend that you review their privacy policy before using such external websites.

SECURITY

We safeguard your privacy using known security standards and procedures and comply with applicable privacy laws. Our Website/VikaOne Mobile Application combines industry-approved physical, electronic, and procedural safeguards to ensure that your information is well protected throughout its life cycle in our infrastructure.

Sensitive data is hashed or encrypted when it is stored in our infrastructure. Sensitive data is decrypted, processed, and immediately re-encrypted or discarded when no longer necessary. We host web services in audited data centers, with restricted access to the data processing servers. Controlled access, recorded and live-monitored video feeds, 24/7 staffed security, and biometrics provided in such data centers ensure that we provide secure hosting.

CONFIDENTIALITY

You further acknowledge that the Platform may contain information that is designated confidential by us and that you shall not disclose such information without our prior written consent. Your information is regarded as confidential and therefore will not be divulged to any third party, unless if legally required to do so to the appropriate authorities. We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail. Any emails sent by us will only be in connection with the provision of agreed services, and you retain sole discretion to seek for discontinuation of such communications at any point in time.

OPT-OUT POLICY

All our users have the opportunity to opt out of receiving non-essential (promotional, marketing-related) communications. Please email info@vikaone.com if you no longer wish to receive any information from us.

CONSENT

By using the Website/VikaOne Mobile Application and/or by providing your information, you consent to the collection and use of the information you disclose on the Website/VikaOne Mobile Application in accordance with this Privacy Policy, including but not limited to your consent for sharing your information as per this privacy policy.

If we decide to change our privacy policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it.

CHANGES TO THIS PRIVACY POLICY

Our privacy policy is subject to change at any time without notice. We may change our Privacy Policy from time to time. Please review this policy periodically to make sure you are aware of any changes.

REVIEWING AND UPDATING PERSONAL INFORMATION

In accordance with the legislation in force, the User has the right to access, rectify and object data concerning himself/herself. Users can access and change the Personal Information and preferences provided when an account is created through the account page or by contacting us. We shall ensure that any Personal Information found to be inaccurate or deficient shall be corrected or amended as feasible.

FEEDBACK & QUESTIONS

If You have any questions, comments, or concerns about Our privacy practices or would like to provide feedback on the services offered on the Website/VikaOne Mobile Application, please contact Our grievance officer by e-mail at info@vikaone.com. Our support centres are operative from Monday to Friday between 10 am and 6 pm (subject to holidays).

DATA COLLECTION
For the purpose of verifying KYC and profile images, the user's Aadhar card and pan card images have either been taken from the gallery or have been captured using the camera.

DATA USAGE
The information gathered is used to confirm the user's KYC, and it will not be used for marketing purposes.

ACCESS AND PERMISSIONS
The information gathered is used to confirm the user's KYC as per the government rule.

SECURITY MEASURES
We have 3 Layer's security on the AWS server and the Website/VikaOne Mobile Application is secure with SSL and data is stored in encryption form for protecting the user data from threat attacks.

USER CONTROL
According to government regulations, we are not permitted to delete the data, and aside from these three pieces of information, we do not collect any additional information from users. Therefore, the user won't be able to delete the data from the VikaOne Mobile Application side.

LEGAL COMPLIANCES
We have ensured all the Apple App Store & Play Store laws and regulations for our system.

CONTACT INFORMATION
If the user has any queries, they can connect with us via the below details from Monday - Saturday between 10 AM - 7 PM
Email: info@vikaone.com
''';

  static const String returns = '''
RETURN POLICY

In case of rejection of a delivery order in accordance with these terms, where payments have been received by PAYVIKA INDIA TECHNOLOGY PVT LTD, such payment shall be returned to you to the bank account linked to your account, subject to the terms and conditions indicated on the platform.

We will process the refund within 3 working days, and it will be credited to the customer account within 7 working days. Please note that in some cases due to unforeseen circumstances the transaction of return might be delayed.
''';

  static const String refund = '''
REFUND POLICY

You should carefully examine the package delivered and shall not accept deliveries where the packaging has been tampered with. If, however, You are of the view that the package delivered has been tampered with, You are required not to accept the parcel and shall immediately intimate Payvika India Technology Pvt. Ltd. at info@vikaone.com and provide such other information as may be required by Payvika India Technology Pvt. Ltd., including digital evidence such as photographs and videos of the package ("Return Request").

Within 1 (One) Business Day of the original package containing the Gold/Silver being delivered back to Payvika India Technology Pvt. Ltd., in the manner indicated by the Company, and upon approval of the Return Request (where the delivery has already been received by You), Payvika India Technology Pvt. Ltd. shall arrange for the re-delivery or pickup of the Delivered Gold/Silver at the shipping address provided by You. The shipping costs for such re-delivery shall be borne by Payvika India Technology Pvt. Ltd.

However, in the event of frivolous, false or unjustified Return Requests made by You, Payvika India Technology Pvt. Ltd. reserves the right to take any action available under applicable law, including blacklisting or blocking Your access to the VikaOne Platform and retaining a reasonable lump sum amount towards administrative and unforeseen expenses.

Upon signing the delivery receipt, You acknowledge that You have received the Delivered Gold/Silver product in accordance with the Delivery Request placed through VikaOne. Payvika India Technology Pvt. Ltd. shall not be liable for any refund or replacement under any circumstances for any subsequent complaints regarding such deliveries or any failure on Your part to comply with these Terms.

It shall be Your responsibility to ensure that You are available to receive the Delivered Gold/Silver at the time of delivery. If You are unavailable, the authorized courier partner may attempt delivery three (3) consecutive times before returning the package to Payvika India Technology Pvt. Ltd. In case the Delivered Gold/Silver is returned, the equivalent quantity shall be credited back to Your VikaOne Gold Wallet, after deducting any applicable charges payable by You, provided that Payvika India Technology Pvt. Ltd. determines that the package has not been tampered with.

If You request re-delivery, all applicable re-delivery charges shall be borne solely by You.

In the event that Payvika India Technology Pvt. Ltd. is unable to deliver the Gold/Silver due to a Force Majeure Event, the Company shall notify You within a reasonable period and may require delivery through an alternative mode. You agree to bear any additional costs or charges required to complete such delivery.

Payvika India Technology Pvt. Ltd. shall not deliver fractional quantities of Gold/Silver below the minimum quantity prescribed by the Company from time to time ("Threshold Quantity"), even if a Customer Request has been made. Customers are advised to periodically check the VikaOne Platform for the latest Threshold Quantity.

Where the Gold/Silver quantity held is below the Threshold Quantity, such Gold/Silver shall instead be sold at the prevailing sale price displayed on the VikaOne Platform, and the corresponding sale proceeds shall be credited to the bank account provided by You. Payvika India Technology Pvt. Ltd. shall not be responsible for any loss arising due to incorrect bank account details furnished by You.

Notwithstanding anything contained in these Terms, Payvika India Technology Pvt. Ltd. reserves the right to reject any Customer Request that does not comply with these Terms and shall notify the Customer of the reasons for such rejection.

If You believe that any transaction or balance reflected in Your VikaOne Wallet does not correspond with the Orders or Customer Requests placed by You, You may contact Payvika India Technology Pvt. Ltd. at info@vikaone.com, and the Company shall investigate and take appropriate corrective action wherever applicable.

Gold/Silver held in the VikaOne Wallet cannot be pledged by You, and the VikaOne Gold Wallet is non-transferable except where expressly permitted by Payvika India Technology Pvt. Ltd. In the event of Your death, and where permitted by the Company, ownership of the Gold/Silver held in the vault and the VikaOne Wallet shall pass to Your nominated legal heir(s) after completion of the Company's due diligence process, provided nominee details have been duly submitted. Thereafter, such legal heir(s) shall be treated as the Customer for all purposes under these Terms.

The VikaOne Platform may display product images for shopping purposes. Due to photography techniques, screen settings or display variations, products may appear slightly different in size or colour from the actual product. Payvika India Technology Pvt. Ltd. shall not be liable for any claim arising from such differences and shall make reasonable efforts to ensure that product information is accurately displayed.

Due to technical or system-related issues beyond the reasonable control of Payvika India Technology Pvt. Ltd., information or prices displayed on the VikaOne Platform may occasionally be inaccurate. The Company reserves the right to correct such errors and shall not be obligated to honour any order placed based on incorrect pricing or inaccurate information.

All prices displayed on the VikaOne Platform are fixed, non-negotiable and subject to change without prior notice.

Upon approval of a return request, the equivalent Gold/Silver quantity shall be re-credited to the Customer's VikaOne Gold Wallet within 3 (Three) working days. Where a monetary refund is applicable, Payvika India Technology Pvt. Ltd. shall process the refund within 3 (Three) working days, and the amount shall ordinarily be credited to the Customer's registered bank account within 7 (Seven) working days, subject to banking timelines. In exceptional circumstances beyond the Company's control, the refund may take additional time.

Customers may cancel a delivery request before the shipment is marked as "Out for Delivery" through the VikaOne mobile application or website under the "My Orders" section.

If an Order is rejected in accordance with these Terms after payment has been received, Payvika India Technology Pvt. Ltd. shall refund the applicable amount to the Customer's registered bank account, subject to these Terms and any other conditions published on the VikaOne Platform.
''';

  static const String shipping = '''
SHIPPING POLICY

The product shipping will be processed within 2 working days after receiving the order request and will be delivered within 10 working days after the processing has been completed.

Please note that in some cases, due to some unforeseen circumstances delivery might get delayed.
''';
}
